[ERROR] There is a conflict between multiple exceptions for assigning the same variable.

This justification is true:
  --> test_func/bad/bad_func.catala_en
   | 
15 |   definition f of x under condition not b consequence equals x * x
   |                                     ^^^^^
   + Article

This justification is true:
  --> test_func/bad/bad_func.catala_en
   | 
14 |   definition f of x under condition (x >= x) consequence equals x + x
   |                                      ^^^^^^
   + Article
