[ERROR] There is a conflict between multiple exceptions for assigning the same variable.

This justification is true:
 --> test_default/bad/conflict.catala_en
  | 
9 |   definition x under condition true consequence equals 0
  |                                ^^^^
  + Article

This justification is true:
 --> test_default/bad/conflict.catala_en
  | 
8 |   definition x under condition true consequence equals 1
  |                                ^^^^
  + Article
